name: Python Unittest

on:
  push:
    branches: [ master, support_test_on_github_actions, support_https ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        use_https: ["yes", "no"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitlfs_with_nginx

    - name: Prepare env.list
      env:
        USE_HTTPS: ${{ matrix.use_https }}
      run: |
        if [ $USE_HTTPS = "yes" ]; then
          sh tests/create_cert.sh
          sed -i "s/^USE_HTTPS=no/USE_HTTPS=yes/" env.list
        fi
        sed -i "s/^SECRET_KEY=0/SECRET_KEY=1/" env.list
        cat env.list

    - name: Run the Docker image
      env:
        USE_HTTPS: ${{ matrix.use_https }}
      run: |
        if [ $USE_HTTPS = "yes" ]; then
          docker run --name gitlfs_container -d --rm --env-file env.list -v $GITHUB_WORKSPACE/tests/cert:/opt/home/ssl:ro -v $GITHUB_WORKSPACE/data:/opt/home/data -p2000:80 gitlfs_with_nginx
        else
          docker run --name gitlfs_container -d --rm --env-file env.list -v $GITHUB_WORKSPACE/data:/opt/home/data -p2000:80 gitlfs_with_nginx
        fi

    - name: Configure git
      run: |
        git config --global user.email "test.runner@example.com"
        git config --global user.name "Test Runner"
        git lfs install

    - name: Run unittest
      run: python -m unittest -v
      env:
        USE_HTTPS: ${{ matrix.use_https }}

    - name: Stop the Docker image
      run: docker stop gitlfs_container
      if: always()
      continue-on-error: true
